### ISSUE TITLE
Licensing, pull requests

### ISSUE THREAD

**Issue by vydd** [Ramarren/cl-geometry#2]
Hello,

I tried using your library, more specifically its polygon triangulation routine, and it crashed when trying to triangulate a simple 13-point polygon (no holes, no intersections). Looking at the code, I noticed you were using ear clipping method, so that wouldn't work for me in a general case anyway.

Digging further, I noticed lots of comments on the implementation being non-optimal, which is not a problem in itself, but seeing that the last real commits to this repository were done 7 years ago, makes me think that this project is abandoned, and that those algorithms are never going to get implemented in a better way.

I want to improve the library, but since there is no licensing information, forking is difficult. Before I commit myself to rewriting this otherwise great piece of work, I'd like to ask the following:
- Is this repository really abandoned, or would you be willing to review pull requests?
- Under what kind of license would you like to distribute this project?

Thank you!

**Comment by Ramarren** [comment]
The library was mostly an exercise from a time when I was learning Common Lisp, so it is very far from perfect. These days I am too busy with work to program in my free time, and I'm afraid have forgotten too much about computational geometry to meaningfully review pull requests, so it is effectively abandoned.

I added LICENSE.txt file with a simplified BSD-style license. Feel free to develop and use this library in any way.

**Comment by vydd** [comment]
Thank you so much for the quick reply and for adding the license.

All the best
