### ISSUE TITLE
intersect-p bug with horizontal line segment

### ISSUE THREAD

**Issue by kg6y-ucd** [Ramarren/cl-geometry#4]
It seems that the return value of intersect-p is incorrect if one of the line segment is horizontal.

```
GEOMETRY> (intersect-p (make-point 0 0)
               (make-point 50 0)
               (make-point 51 10)
               (make-point 100 0))
T
GEOMETRY> 
```

**Comment by Ramarren** [comment]
Thanks again! I wrote this code about nine years ago before I learnt the value of unit tests and such, and hasn't used it much since, so unfortunately it seems to have a bunch of elementary errors.
