### ISSUE TITLE
Is cl-geometry actively maintained

### ISSUE THREAD

**Issue by mirkov** [Ramarren/cl-geometry#5]
I would like to use cl-geometry's bounding boxes.  I would add some facilities, such as other primitives and their derivatives.

Will you consider contributions or address issues?

Thank you,

Mirko

**Comment by vydd** [comment]
@mirkov Hi! I took it upon myself to maintain this repo at https://github.com/vydd/cl-geometry (which is what QL is tracking now) and review PRs after the discussion in https://github.com/Ramarren/cl-geometry/issues/2 .

I did much less development than I intended, but I don't plan to abandon the library, as I'm using it in https://github.com/vydd/sketch and think it's generally useful.

So, if you post a PR to that repo, I'll be happy to review it and merge it to master.

**Comment by mirkov** [comment]
Thanks Danilo,

I will clone cl-geometry from [https://github.com/vydd/cl-geometry](url).  I will post PR's to that repo for your consideration.

Best,

Mirko
